name: Build and Archive Artifact
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
       
      - name: Build with Maven
        run: mvn clean install

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: /home/runner/.m2/repository/com/mycompany/app/my-app/1.0-SNAPSHOT/my-app-1.0-SNAPSHOT.jar

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: /home/runner/.m2/repository/com/mycompany/app/my-app/1.0-SNAPSHOT/my-app-1.0-SNAPSHOT.jar

      - name: Copy Artifact to src Directory
        run: cp -r /home/runner/.m2/repository/com/mycompany/app/my-app/1.0-SNAPSHOT/my-app-1.0-SNAPSHOT.jar ./

