name: Build and Save Artifact

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Create target directory
        run: mkdir -p target

      - name: Copy JAR artifact to target
        run: mv /home/runner/work/simple-java-maven-app/simple-java-maven-app/target/my-app-1.0-SNAPSHOT.jar target/

   

  #deploy:
  #  runs-on: ubuntu-latest
  #  steps:
  #    - name: Checkout code
  #      uses: actions/checkout@v2
#
#      # Other steps (e.g., build, test)
#
 #     - name: Download the release artifact
  #      uses: actions/download-artifact@v2
  #      with:
   #       name: my-artifact
    #      path: target/
